[default]
REDIS_HOST="localhost"
SECRET_KEY="NOT_SECURE_SECRET_KEY"
CONFIRMATION_KEY="NOT_SECURE_CONFIRMATION_KEY"
LOG_LEVEL="DEBUG"
LOG_BACKTRACE=true
API_MAIL_URL ="http://localhost:7777"
ACCESS_TOKEN_EXPIRE_MINUTES=30
ALGORITHM = "HS256"
COMPANY="MY_COMPANY"
ENVIRONMENT="development"
ZIP_CODE_SOURCE ="47590000"



[testing]
DATABASE_URL="postgresql://partyoudbuser:partyou123@localhost/test"
API_MAIL_URL="https://testapi.com/"
ACCESS_TOKEN_EXPIRE_MINUTES=15
LOG_LEVEL="DEBUG"
LOG_BACKTRACE=true
